---
include:
  - project: "Bigouden/gitlab-ci-templates"
    file: ".gitlab-ci-docker.yml"

.standalone:
  image:
    name: $CONTAINER_TEST_IMAGE
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  dependencies: []

variables:
  HADOLINT_ALLOW_FAILURE: "true"

stages:
  - Quality
  - Security
  - Build
  - Commands
  - Inspect
  - Release
  - Clean

Docker CLI:
  stage: Commands
  extends: .standalone
  script:
    - docker -v

Paranoia CLI:
  stage: Commands
  extends: .standalone
  script:
    - paranoia -h
